version: '3.7'

services:

  cliente_api:
    environment:
      SECRET_KEY: ${SECRET_KEY}
      PATH_LOGS: ${PATH_LOGS}
      NAME_BD: ${NAME_BD}
      USR_BD: ${USR_BD}
      PASS_BD: ${PASS_BD}
      HOSTDJ: bd_cliente
      PORTDJ: ${PORTDJ}
      USR_TERMINAL: ${USR_TERMINAL}
      PASS_TERMINAL: ${PASS_TERMINAL}
      URL_TERMINAL: ${URL_TERMINAL}
      USR_MASTER_SERVICE: ${USR_MASTER_SERVICE}
      PASS_MASTER_SERVICE: ${PASS_MASTER_SERVICE}
    build: ./contenedor_clienteAPI
    restart: always
    pid: "host"
    container_name: ssa_cliente_api
    volumes:
      - ./contenedor_clienteAPI/cliente_monitorAPI:/code
      - ./contenedor_clienteAPI/LOGS_CLIENTE:/LOGS_CLIENTE
    depends_on:
      - bd_cliente
      
  bd_cliente:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${PASS_BD}
      MYSQL_DATABASE: ${NAME_BD}
    volumes:
      - ./contenedor_clienteAPI/data:/var/lib/mysql

  nginx:
    image: nginx
    restart: always
    environment: 
      - NGINX_HOST=cliente_api
    volumes:
      - ./contenedor_clienteAPI/nginx:/etc/nginx/conf.d
      - ./contenedor_clienteAPI/certs:/certs
    depends_on:
      - cliente_api
    ports:
      - 9999:443
